### ISSUE TITLE
please add repoview links 

### ISSUE THREAD

**Issue by sergiomb2** [UnitedRPMs/unitedrpms.github.io#1]
https://goo.gl/Yn0hWI redirects to x86_64/repoview/index.html 
Maybe also we should add srpm/repoview/index.html and x86_64/debug/repoview/index.html links

**Comment by paulcarroty** [comment]
> https://goo.gl/Yn0hWI redirects to x86_64/repoview/index.html 

Added to website, thx.

> we should add srpm/repoview/index.html and x86_64/debug/repoview/index.html links

I don't think that these links is good related to website and can be interested for used. But, if you need it - just add it.

**Comment by sergiomb2** [comment]
thanks
