### ISSUE TITLE
Need add mirrors, i suggest mirror.yandex.ru

### ISSUE THREAD

**Issue by x09** [UnitedRPMs/unitedrpms.github.io#13]
Hi

May be try to communicate with Yandex team (http://mirror.yandex.ru) for add mirror repo.

> Welcome to Yandex Linux mirror, hosted at Yandex, Russian Federation.
> My hostname is node04d.mirror.yandex.net
> Contacts: opensource@yandex-team.ru
> We support http, ftp and rsync protocols.

Others repos already added to http://mirror.yandex.ru/fedora/, may bee unitedrpms too ?

**Comment by paulcarroty** [comment]
@sergiomb2 @kuboosoft

**Comment by sergiomb2** [comment]
be my guest ,

**Comment by kuboosoft** [comment]
@x09 Welcome!!

**Comment by paulcarroty** [comment]
https://www.google.com.ua/#q=yandex+bar+malware&*

It's like ask something from drug traffickers or kids porno sellers. I definitely not support it. 

Otherwise, our repos is public and anyone can create the mirror.

**Comment by kuboosoft** [comment]
Yandex is a simply domain from russia.... Remember our repository doesn't support all world (banned countries bla bla bla...) La fin justifie les moyens.  @x09 You are free if you want open a mirror in yandex...
