### ISSUE TITLE
Don't rely on GitHub Pages HTTPS

### ISSUE THREAD

**Issue by cben** [UnitedRPMs/unitedrpms.github.io#2]
Current instruction use
https://unitedrpms.github.io/URPMS-GPG-PUBLICKEY-Fedora-24
https://unitedrpms.github.io/unitedrpms.repo
which are served by GitHub Pages.
While that works, it's unfortunately not entirely secure [https://github.com/isaacs/github/issues/156] — GitHub have indicated their connection to the CDN seving Pages is unsecured, so a man-in-the-middle attack there could make users trust a malicious key + add a malicious repo.

Possible solutions:
- Point users to the (less pretty) raw file urls (unlike Pages, normal github.com functionality is fully secure):
  https://raw.githubusercontent.com/UnitedRPMs/unitedrpms.github.io/master/URPMS-GPG-PUBLICKEY-Fedora-24
  https://raw.githubusercontent.com/UnitedRPMs/unitedrpms.github.io/master/unitedrpms.repo
  - Meta-issue: if attacker can corrupt responses from unitedrpms.github.io/, he can rewrite the *instructions themselves* to point to any unsecure URL (in particular, pointing back to unitedrpms.github.io would look very unsuspicious).  I do think delivering normally secure instructions over insecure channel is better than nothing.
- Deeper solution: Don't use Pages for instructions.  Just put them in e.g. README.md.
- Or host elsewhere.  Specifically, I think GitLab Pages support HTTPS fully.

**Comment by paulcarroty** [comment]
@cben thanks for the excellent report!

Now fixed with https://github.com/UnitedRPMs/unitedrpms.github.io/commit/c068b9510213a52841bf92e16aca119505204e8b, https://github.com/UnitedRPMs/unitedrpms.github.io/commit/86d6bf0d79255ef011102d6e32d3f52a75deb064.

**Comment by cben** [comment]
unitedrpms.repo and fedora-enjoy24.repo still have `gpgkey=` field pointing to github pages.
(`mirrorlist=` too, that's less critical for security)

**Comment by sergiomb2** [comment]
> Deeper solution: Don't use Pages for instructions .

yeah looks the only hyper secure solution , but for me I not accept this issue , or we change all webpage or we don't have a complete solution
change repo to [1] looks to me an incomplete solution , I think we have better things to worry about 
[1]
```
mirrorlist=https://raw.githubusercontent.com/UnitedRPMs/unitedrpms.github.io/master/mirrorlist_enjoy24_x86_64.txt
gpgkey=https://raw.githubusercontent.com/UnitedRPMs/unitedrpms.github.io/master/URPMS-GPG-PUBLICKEY-Fedora-24
```

**Comment by paulcarroty** [comment]
We *now* don't use GH pages for instructions and I'll disable it from repo configs probably tomorrow.

**Comment by kuboosoft** [comment]
mmm, It is easy, we can move the gpg key, outside the github site, example here https://github.com/UnitedRPMs/packages

**Comment by paulcarroty** [comment]
@kuboosoft change  the URL, not key destination.

**Comment by kuboosoft** [comment]
> GitHub have indicated their connection to the CDN seving Pages is unsecured, so a man-in-the-middle attack there could make users trust a malicious key + add a malicious repo

@paulcarroty  Nothing is secure in this life haha, but we can sign also the repository... and give to user option enable or not it... a "asc" [example](https://sourceforge.net/projects/postinstaller/files/fedora/releases/24/x86_64/repodata/) 

[We can sign a repository after it has been created by running](http://yum.baseurl.org/wiki/RepoCreate)

**Comment by paulcarroty** [comment]
- [x] Add the repodata signing to `add_packages.sh`
- [x] Sign repodata
- [ ] Delete Gthub Pages from repository config

**Comment by sergiomb2** [comment]
> @paulcarroty Nothing is secure in this life haha, but we can sign also the repository... and give to user option enable or not it... a "asc" example
> 
> We can sign a repository after it has been created by running http://yum.baseurl.org/wiki/RepoCreate

on point 3 says : "This will create a repomd.xml.asc file in the repodata directory which for modern versions of yum this will allow yum to verify that the repository metadata came from the owner of the gpg key. " 
but I don't see how I make sure (enable gpg check) on repository metadata, this has ever worked ? (on yum or dnf ) ? I maybe will ask how enable gpg check on repository metadata in Fedora devel Mailing list .
Best regards.

**Comment by kuboosoft** [comment]
@sergiomb2 
a simple example...
```
[repo-foo]
name=foo
baseurl=https://foo/
enabled=1
metadata_expire=2d
gpgcheck=1
repo_gpgcheck=1 
gpgkey=https://foo/RPM-GPG-KEY-foo
skip_if_unavailable=1
```

**Comment by paulcarroty** [comment]
@sergiomb2 

> repo_gpgcheck Either '1' or '0'. This tells yum whether or not it should perform a GPG signature check on the repodata. When this is set in the [main] section it sets the default for all repositories. The default is '0'.
 
http://linux.die.net/man/5/yum.conf

**Comment by kuboosoft** [comment]
Hey!! read it [haha](https://bugzilla.rpmfusion.org/show_bug.cgi?id=569)

**Comment by cben** [comment]
As luck would have it, a few days later Github Pages finally became secure:
https://github.com/blog/2186-https-for-github-pages

**Comment by paulcarroty** [comment]
We're also force SSL for unitedrpms.github.io with redirection to https.
