### ISSUE TITLE
Conflict with fedora openh264 repository

### ISSUE THREAD

**Issue by HeikoAdams** [UnitedRPMs/unitedrpms.github.io#3]
The package gstreamer1-plugins-bad-freeworld conflicts with gstreamer1-plugin-openh264 from fedora openh264 repository:

> file /usr/lib64/gstreamer-1.0/libgstopenh264.so from install of gstreamer1-plugins-bad-freeworld-1.8.1-1.fc24.x86_64 conflicts with file from package gstreamer1-plugin-openh264-1.6.1-2.fc24.x86_64

**Comment by sergiomb2** [comment]
duplicated of https://github.com/UnitedRPMs/gstreamer1-plugins-bad-freeworld/issues/1
Thanks
