### ISSUE TITLE
Please don't use MD5

### ISSUE THREAD

**Issue by genodeftest** [UnitedRPMs/unitedrpms.github.io#4]
Readme.md has a MD5 checksum.

MD5 is so 1990ies...
SHA-1 is so 2000s...
SHA-2 is the new sh**!

/Irony

MD5 is known to be broken and thus quite useless. Please use a modern, reasonable secure algorithm instead, e.g. SHA-2 (sha512).

**Comment by kuboosoft** [comment]
@genodeftest Don't worry, updated now ;)

**Comment by paulcarroty** [comment]
Lol
