### ISSUE TITLE
UnitedRPMs website points to missing/hidden contributor list

### ISSUE THREAD

**Issue by ferdnyc** [UnitedRPMs/unitedrpms.github.io#9]
The [UnitedRPMs website](https://unitedrpms.github.io/) section "Why doesn't UnitedRPMs contribute to RPMFusion?" says...

> You can find a list of all contributors [here](https://github.com/orgs/UnitedRPMs/people), the specs and source code are also available on Github.

But actually following that link... (not so much).

![screenshot from 2016-10-24 17-52-18](https://cloud.githubusercontent.com/assets/538020/19665636/f74fd796-9a13-11e6-9ab6-7ffd42d3573e.png)

**Comment by paulcarroty** [comment]
Hello, NSA :smiley: 

@sergiomb2 , @kuboosoft and /me should change their membership to public.

**Comment by paulcarroty** [comment]
Fixed by https://github.com/UnitedRPMs/unitedrpms.github.io/commit/07da29bd3fdfb9ec5e65810720f00dce56519a92.
